apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ecsdrtyu
  description: provision ECS using backstage
spec:
  owner: group:default/guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecsdrtyu
  description: provision ECS using backstage
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: prayankag/ecsdrtyu/actions    
spec:
  type: service
  owner: group:default/guests
  lifecycle: experimental
  system: ecsdrtyu
  providesApis:
    - ecsdrtyu
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ecsdrtyu
  description: provision ECS using backstage
spec:
  type: internal
  lifecycle: experimental
  owner: group:default/guests
  system: ecsdrtyu
  definition: "provision ECS using backstage"
